version: "2"
services:
  moodle:
    build: .
    image: moodle-docker:3.9
#    labels:
#      deck-chores.moodle.command: '/usr/local/bin/php /var/www/moodle/admin/cli/cron.php'
#      deck-chores.moodle.interval: 'every minute'
#      deck-chores.moodle.user: 'www-data'
#    environment:
#      PUID: 33
#      PGID: 33
#      NO_MOODLE_CRON: 'Y'
    volumes:
      - ./instance/www:/data
#      - ./moodle-scripts:/moodle-scripts
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 'secret-password'
      POSTGRES_USER: 'moodle-user'
      POSTGRES_DB: 'moodle-db'
    volumes:
      - ./instance/db:/var/lib/postgresql/data

#  deckchores:
#    image: funkyfuture/deck-chores:1
#    environment:
#      TIMEZONE: America/Thunder_Bay
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
