version: "2"
services:
  moodle:
    container_name: moodle
    build: .
    image: moodle-docker:3.9
#    environment:
#      PUID: 33
#      PGID: 33
#      NO_MOODLE_CRON: 'Y'
    volumes:
      - ./instance/www:/data
      - ./moodle-scripts:/moodle-scripts
    ports:
      - 80:80
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 'secret-password'
      POSTGRES_USER: 'moodle-user'
      POSTGRES_DB: 'moodle-db'
    volumes:
      - ./instance/db:/var/lib/postgresql/data
    restart: unless-stopped
