version: "2"
services:
  moodle:
    container_name: moodle
    build: .
    image: moodle-docker:latest
    environment:
      TZ: "America/Thunder_Bay"
      AUTO_UPGRADE: "Y"
#      BACKUP_CRON: "*/15 * * * *"
      PLUGINS_CRON: "*/15 * * * *"
#      UPDATE_CRON: "*/5 * * * *"
#      RESTORE_CRON: "*/4 * * * *"
#      PUID: 33
#      PGID: 33
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_NAME: test
      MOODLE_DATABASE_USER: testuser
      MOODLE_DATABASE_PASSWORD: "N0t A G00d Passw0rd"
      MOODLE_WWW_ROOT: http://localhost
      MOODLE_CACHE_DIR: /moodle/cache
      MOODLE_TEMP_DIR: /moodle/temp
      MOODLE_USERNAME: testadmin
      MOODLE_PASSWORD: "N0t A G00d Passw0rd"
      MOODLE_EMAIL: "wade@contactnorth.ca"
      MOODLE_SITE_NAME: "Moodle Test Site"
      MOODLE_SITE_SHORTNAME: TEST
      BBB_SERVER_URL: http://test-install.blindsidenetworks.com/bigbluebutton/
      BBB_SHARED_SECRET: 8cd8ef52e8e101574e400365b55e11a6
    volumes:
      - ./instance/data:/data
      - ./instance/moodle:/var/www/moodle
      - ./moodle-scripts:/moodle-scripts
    ports:
      - 80:80
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: "N0t A G00d Passw0rd"
    volumes:
      - ./instance/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
