version: "2"
services:
  moodle:
    container_name: moodle
    build: .
    image: moodle-docker:3.9
    env_file:
      - ./instance/.env
    environment:
      TZ: "America/Thunder_Bay"
      GIT_URL: "https://github.com/moodle/moodle.git"
#      MOODLE_BRANCH: "MOODLE_310_STABLE"
#      AUTO_UPGRADE: "Y"
#      MOODLE_CRON: ""
#      BACKUP_CRON: "*/15 * * * *"
      PLUGINS_CRON: "*/15 * * * *"
#      UPDATE_CRON: "*/5 * * * *"
#      RESTORE_CRON: "*/4 * * * *"
#      PUID: 33
#      PGID: 33
    volumes:
      - ./instance/data:/data
      - ./instance/moodle:/var/www/moodle
      - ./moodle-scripts:/moodle-scripts
    ports:
      - 80:80
    depends_on:
      - db
      - av
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: $MOODLE_DATABASE_NAME
      POSTGRES_USER: $MOODLE_DATABASE_USER
      POSTGRES_PASSWORD: $MOODLE_DATABASE_PASSWORD
    volumes:
      - ./instance/db:/var/lib/postgresql/data
    restart: unless-stopped

#  db:
#    container_name: mariadb
#    image: mariadb:10.5
#    command: >
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_bin
#      --innodb_file_per_table=On
#      --wait-timeout=28800
#    env_file:
#      - ./instance/.env
#    environment:
#      MARIADB_ROOT_PASSWORD: 'super-secret-password'
#      MARIADB_DATABASE: $MOODLE_DATABASE_NAME
#      MARIADB_USER: $MOODLE_DATABASE_USER
#      MARIADB_PASSWORD: $MOODLE_DATABASE_PASSWORD
#    volumes:
#      - ./instance/mariadb:/var/lib/mysql
#    restart: unless-stopped

  av:
    container_name: clamav
    image: tiredofit/clamav:latest
    environment:
      MAX_FILE_SIZE: $CLAMAV_MAX_SIZE
      MAX_SCAN_SIZE: $CLAMAV_MAX_SIZE
      PCRE_MAX_FILE_SIZE: $CLAMAV_MAX_SIZE
      STREAM_MAX_LENGTH: $CLAMAV_MAX_SIZE
    volumes:
      - ./instance/clamav/data:/data
      - ./instance/clamav/logs:/logs
    restart: unless-stopped
